# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install transformers torch datasets scikit-learn pandas numpy matplotlib seaborn -q

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import torch
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from datasets import load_dataset
import matplotlib.pyplot as plt
import seaborn as sns

print("✅ All imports done")
print(f"GPU available: {torch.cuda.is_available()}")
print(f"Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")

# CELL 3 — Load HC3
print("Loading HC3...")
import requests, json

rows = []
url = "https://huggingface.co/datasets/Hello-SimpleAI/HC3/resolve/main/all.jsonl"
response = requests.get(url)
lines = response.text.strip().split("\n")

for line in lines:
    row = json.loads(line)
    source = row.get("source", "general")
    for ans in row.get("human_answers", []):
        if ans and len(ans.strip()) > 50:
            rows.append({"text": ans.strip(), "label": 0, "domain": source})
    for ans in row.get("chatgpt_answers", []):
        if ans and len(ans.strip()) > 50:
            rows.append({"text": ans.strip(), "label": 1, "domain": source})

hc3 = pd.DataFrame(rows)
print(f"✅ HC3 loaded: {hc3.shape}")
print(hc3["label"].value_counts())
print(hc3["domain"].value_counts())
print("\nSample human:")
print(hc3[hc3["label"]==0]["text"].iloc[0][:200])
print("\nSample AI:")
print(hc3[hc3["label"]==1]["text"].iloc[0][:200])

# CELL 4 — Load NYT
print("Loading NYT...")
ds_nyt = load_dataset("gsingh1-py/train", split="train")
nyt_raw = ds_nyt.to_pandas()

nyt_rows = []
ai_cols = ['gemma-2-9b', 'mistral-7B', 'qwen-2-72B', 'llama-8B',
           'accounts/yi-01-ai/models/yi-large', 'GPT_4-o']

for _, row in nyt_raw.iterrows():
    if pd.notna(row['Human_story']) and len(str(row['Human_story']).strip()) > 50:
        nyt_rows.append({"text": str(row['Human_story']).strip(), "label": 0, "domain": "news"})
    for col in ai_cols:
        if pd.notna(row[col]) and len(str(row[col]).strip()) > 50:
            nyt_rows.append({"text": str(row[col]).strip(), "label": 1, "domain": "news"})

nyt_df = pd.DataFrame(nyt_rows)
print(f"✅ NYT: {nyt_df.shape}")
print(nyt_df["label"].value_counts())

# CELL 5 — Load RAID full
print("Loading RAID...")
ds_raid = load_dataset("liamdugan/raid")
print(f"Splits: {ds_raid.keys()}")

raid_raw = ds_raid["train"].to_pandas()
print(f"Shape: {raid_raw.shape}")
print(f"Domains:\n{raid_raw['domain'].value_counts()}")
print(f"Models:\n{raid_raw['model'].value_counts()}")

raid_raw["text"] = raid_raw["generation"]
raid_raw["label"] = raid_raw["model"].apply(lambda x: 0 if x == "human" else 1)
print(f"\nLabel counts:\n{raid_raw['label'].value_counts()}")

# CELL 6 — Balance and sample all 3 datasets
print("Balancing all datasets...")

# ── HC3 ──────────────────────────────────────────
hc3_h = hc3[hc3["label"]==0].sample(5000, random_state=42)
hc3_a = hc3[hc3["label"]==1].sample(5000, random_state=42)
hc3_bal = pd.concat([hc3_h, hc3_a]).sample(frac=1, random_state=42).reset_index(drop=True)
print(f"✅ HC3 balanced: {hc3_bal.shape}")
print(hc3_bal["label"].value_counts())

# ── NYT ──────────────────────────────────────────
nyt_h = nyt_df[nyt_df["label"]==0].sample(5000, random_state=42)
nyt_a = nyt_df[nyt_df["label"]==1].sample(5000, random_state=42)
nyt_bal = pd.concat([nyt_h, nyt_a]).sample(frac=1, random_state=42).reset_index(drop=True)
print(f"✅ NYT balanced: {nyt_bal.shape}")
print(nyt_bal["label"].value_counts())

# ── RAID ─────────────────────────────────────────
# Sample evenly across all 8 domains
raid_rows = []
for domain in raid_raw["domain"].unique():
    d = raid_raw[raid_raw["domain"]==domain]
    h = d[d["label"]==0].sample(min(625, len(d[d["label"]==0])), random_state=42)
    a = d[d["label"]==1].sample(min(625, len(d[d["label"]==1])), random_state=42)
    raid_rows.append(pd.concat([h, a]))

raid_bal = pd.concat(raid_rows).sample(frac=1, random_state=42).reset_index(drop=True)
raid_bal = raid_bal[["text","label","domain"]]
print(f"✅ RAID balanced: {raid_bal.shape}")
print(raid_bal["label"].value_counts())
print(raid_bal["domain"].value_counts())

# CELL 7 — Train/Test splits for all 3 datasets
print("Creating train/test splits...")

# HC3
X_tr_hc3, X_te_hc3, y_tr_hc3, y_te_hc3 = train_test_split(
    hc3_bal["text"], hc3_bal["label"],
    test_size=0.2, random_state=42, stratify=hc3_bal["label"]
)

# NYT
X_tr_nyt, X_te_nyt, y_tr_nyt, y_te_nyt = train_test_split(
    nyt_bal["text"], nyt_bal["label"],
    test_size=0.2, random_state=42, stratify=nyt_bal["label"]
)

# RAID
X_tr_raid, X_te_raid, y_tr_raid, y_te_raid = train_test_split(
    raid_bal["text"], raid_bal["label"],
    test_size=0.2, random_state=42, stratify=raid_bal["label"]
)

print(f"✅ HC3  — Train: {len(X_tr_hc3)}  Test: {len(X_te_hc3)}")
print(f"✅ NYT  — Train: {len(X_tr_nyt)}  Test: {len(X_te_nyt)}")
print(f"✅ RAID — Train: {len(X_tr_raid)}  Test: {len(X_te_raid)}")

# CELL 8 — Classical Models (NB, LR, SVM) on all 3 datasets
def run_classical(X_train, X_test, y_train, y_test, dataset_name):
    print(f"\n{'='*50}")
    print(f"CLASSICAL MODELS — {dataset_name}")
    print(f"{'='*50}")
    results = {}

    # CountVec for NB
    cvec = CountVectorizer(stop_words="english", max_features=5000)
    Xtr_c = cvec.fit_transform(X_train)
    Xte_c = cvec.transform(X_test)

    # TF-IDF for LR + SVM
    tfidf = TfidfVectorizer(stop_words="english", max_features=5000)
    Xtr_t = tfidf.fit_transform(X_train)
    Xte_t = tfidf.transform(X_test)

    # Naive Bayes
    nb = MultinomialNB()
    nb.fit(Xtr_c, y_train)
    nb_pred = nb.predict(Xte_c)
    nb_acc = accuracy_score(y_test, nb_pred)
    print(f"\nNaive Bayes:          {nb_acc:.4f}")
    print(classification_report(y_test, nb_pred, target_names=["Human","AI"]))
    results["Naive Bayes"] = nb_acc

    # Logistic Regression
    lr = LogisticRegression(max_iter=1000)
    lr.fit(Xtr_t, y_train)
    lr_pred = lr.predict(Xte_t)
    lr_acc = accuracy_score(y_test, lr_pred)
    print(f"Logistic Regression:  {lr_acc:.4f}")
    print(classification_report(y_test, lr_pred, target_names=["Human","AI"]))
    results["Logistic Regression"] = lr_acc

    # SVM
    svm = LinearSVC(max_iter=2000)
    svm.fit(Xtr_t, y_train)
    svm_pred = svm.predict(Xte_t)
    svm_acc = accuracy_score(y_test, svm_pred)
    print(f"Linear SVM:           {svm_acc:.4f}")
    print(classification_report(y_test, svm_pred, target_names=["Human","AI"]))
    results["Linear SVM"] = svm_acc

    # Top features
    feats = tfidf.get_feature_names_out()
    coefs = lr.coef_[0]
    top_ai    = [feats[i] for i in np.argsort(coefs)[-10:]]
    top_human = [feats[i] for i in np.argsort(coefs)[:10]]
    print(f"Top → AI:    {top_ai}")
    print(f"Top → Human: {top_human}")

    return results

# Run on all 3
results_hc3  = run_classical(X_tr_hc3,  X_te_hc3,  y_tr_hc3,  y_te_hc3,  "HC3")
results_nyt  = run_classical(X_tr_nyt,  X_te_nyt,  y_tr_nyt,  y_te_nyt,  "NYT")
results_raid = run_classical(X_tr_raid, X_te_raid, y_tr_raid, y_te_raid, "RAID")

print("\n✅ All classical models done!")

# CELL 9 — DistilBERT fine-tuning on all 3 datasets
MODEL_NAME = "distilbert-base-uncased"
tokenizer  = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)
device     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using: {device}")

class TextDataset(Dataset):
    def __init__(self, texts, labels, max_len=256):
        self.enc    = tokenizer(list(texts), truncation=True, padding=True,
                                max_length=max_len, return_tensors="pt")
        self.labels = torch.tensor(list(labels), dtype=torch.long)
    def __len__(self): return len(self.labels)
    def __getitem__(self, i):
        return {k: v[i] for k, v in self.enc.items()}, self.labels[i]

def run_bert(X_train, X_test, y_train, y_test, name, epochs=3):
    print(f"\n{'='*50}")
    print(f"DISTILBERT — {name}")
    print(f"{'='*50}")
    train_dl = DataLoader(TextDataset(X_train, y_train), batch_size=32, shuffle=True)
    test_dl  = DataLoader(TextDataset(X_test,  y_test),  batch_size=64)
    model    = DistilBertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2).to(device)
    optimizer= AdamW(model.parameters(), lr=2e-5)
    for epoch in range(epochs):
        model.train()
        total_loss, correct, total = 0, 0, 0
        for batch_inputs, batch_labels in train_dl:
            batch_inputs = {k: v.to(device) for k, v in batch_inputs.items()}
            batch_labels = batch_labels.to(device)
            optimizer.zero_grad()
            out = model(**batch_inputs, labels=batch_labels)
            out.loss.backward()
            optimizer.step()
            total_loss += out.loss.item()
            correct    += (out.logits.argmax(1) == batch_labels).sum().item()
            total      += len(batch_labels)
        print(f"  Epoch {epoch+1}/{epochs} — loss={total_loss/len(train_dl):.4f}  acc={correct/total:.4f}")
    model.eval()
    preds, labels = [], []
    with torch.no_grad():
        for batch_inputs, batch_labels in test_dl:
            batch_inputs = {k: v.to(device) for k, v in batch_inputs.items()}
            preds.extend(model(**batch_inputs).logits.argmax(1).cpu().numpy())
            labels.extend(batch_labels.numpy())
    acc = accuracy_score(labels, preds)
    print(f"\n  Test Accuracy: {acc:.4f}")
    print(classification_report(labels, preds, target_names=["Human","AI"]))
    return acc

bert_hc3  = run_bert(X_tr_hc3,  X_te_hc3,  y_tr_hc3,  y_te_hc3,  "HC3")
bert_nyt  = run_bert(X_tr_nyt,  X_te_nyt,  y_tr_nyt,  y_te_nyt,  "NYT")
bert_raid = run_bert(X_tr_raid, X_te_raid, y_tr_raid, y_te_raid, "RAID")

print(f"\n✅ BERT done!")
print(f"HC3:  {bert_hc3:.4f}")
print(f"NYT:  {bert_nyt:.4f}")
print(f"RAID: {bert_raid:.4f}")

# CELL 10 — Generate all plots
import matplotlib.pyplot as plt
import numpy as np

datasets = ["HC3\n(Medical/Legal)", "NYT\n(News)", "RAID\n(Multi-domain)"]
models   = ["Naive Bayes", "Logistic Reg.", "Linear SVM", "DistilBERT"]

scores = {
    "Naive Bayes":      [results_hc3["Naive Bayes"],  results_nyt["Naive Bayes"],  results_raid["Naive Bayes"]],
    "Logistic Reg.":    [results_hc3["Logistic Regression"], results_nyt["Logistic Regression"], results_raid["Logistic Regression"]],
    "Linear SVM":       [results_hc3["Linear SVM"],   results_nyt["Linear SVM"],   results_raid["Linear SVM"]],
    "DistilBERT":       [bert_hc3,                    bert_nyt,                    bert_raid],
}

# Plot 1 — Grouped bar chart
fig, ax = plt.subplots(figsize=(12, 6))
x   = np.arange(len(datasets))
w   = 0.18
colors = ["#1A3A6B","#2A5A9B","#0D9488","#14B8A6"]
for idx, (model, vals) in enumerate(scores.items()):
    bars = ax.bar(x + idx*w, [v*100 for v in vals], w,
                  label=model, color=colors[idx])
    for bar in bars:
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
                f"{bar.get_height():.1f}", ha="center", fontsize=8, fontweight="bold")
ax.set_xticks(x + w*1.5)
ax.set_xticklabels(datasets, fontsize=12)
ax.set_ylim(55, 105)
ax.set_ylabel("Accuracy (%)", fontsize=13)
ax.set_title("Model Accuracy Across All Datasets", fontsize=15, fontweight="bold")
ax.legend(fontsize=11)
ax.spines[["top","right"]].set_visible(False)
plt.tight_layout()
plt.savefig("accuracy_comparison.png", dpi=150)
plt.show()
print("✅ Plot 1 saved")

# Plot 2 — Confusion matrix RAID BERT (most interesting)
from sklearn.metrics import ConfusionMatrixDisplay
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# Rerun predictions for confusion matrices
for ax, (X_tr, X_te, y_tr, y_te, name) in zip(axes, [
    (X_tr_hc3,  X_te_hc3,  y_tr_hc3,  y_te_hc3,  "HC3"),
    (X_tr_nyt,  X_te_nyt,  y_tr_nyt,  y_te_nyt,  "NYT"),
    (X_tr_raid, X_te_raid, y_tr_raid, y_te_raid, "RAID"),
]):
    tfidf = TfidfVectorizer(stop_words="english", max_features=5000)
    svm   = LinearSVC(max_iter=2000)
    svm.fit(tfidf.fit_transform(X_tr), y_tr)
    preds = svm.predict(tfidf.transform(X_te))
    cm    = confusion_matrix(y_te, preds)
    disp  = ConfusionMatrixDisplay(cm, display_labels=["Human","AI"])
    disp.plot(ax=ax, colorbar=False, cmap="Blues")
    ax.set_title(f"SVM — {name}", fontsize=12, fontweight="bold")

plt.suptitle("Confusion Matrices (Linear SVM)", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("confusion_matrices.png", dpi=150)
plt.show()
print("✅ Plot 2 saved")

# Plot 3 — Difficulty comparison
fig, ax = plt.subplots(figsize=(8, 5))
bert_scores = [bert_hc3*100, bert_nyt*100, bert_raid*100]
colors_d    = [C if C else "#0D9488" for C in ["#0D9488","#1A3A6B","#7C3AED"]]
bars = ax.bar(datasets, bert_scores, color=["#0D9488","#1A3A6B","#7C3AED"], width=0.4)
for bar in bars:
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
            f"{bar.get_height():.1f}%", ha="center", fontsize=13, fontweight="bold")
ax.set_ylim(70, 105)
ax.set_ylabel("DistilBERT Accuracy (%)", fontsize=13)
ax.set_title("Dataset Difficulty (DistilBERT)", fontsize=14, fontweight="bold")
ax.spines[["top","right"]].set_visible(False)
plt.tight_layout()
plt.savefig("dataset_difficulty.png", dpi=150)
plt.show()
print("✅ Plot 3 saved")

print("\n✅ All plots done!")

# Quick check — make sure all results are still in memory
print("HC3 results:",  results_hc3)
print("NYT results:",  results_nyt)
print("RAID results:", results_raid)
print("BERT HC3:",     bert_hc3)
print("BERT NYT:",     bert_nyt)
print("BERT RAID:",    bert_raid)

# CELL 11 — Input/Output Examples (for slides)
print("="*55)
print("INPUT / OUTPUT EXAMPLES")
print("="*55)

# Re-run SVM for predictions
tfidf_ex = TfidfVectorizer(stop_words="english", max_features=5000)
svm_ex   = LinearSVC(max_iter=2000)
svm_ex.fit(tfidf_ex.fit_transform(X_tr_hc3), y_tr_hc3)
preds_hc3 = svm_ex.predict(tfidf_ex.transform(X_te_hc3))

label_map = {0: "HUMAN", 1: "AI"}

for dataset, X_te, y_te, preds, name in [
    (None, X_te_hc3, y_te_hc3, preds_hc3, "HC3 (Medical/Legal)"),
]:
    print(f"\n--- {name} ---")
    X_list = list(X_te)
    y_list = list(y_te)
    p_list = list(preds)

    correct   = [(X_list[i], y_list[i], p_list[i]) for i in range(len(y_list)) if y_list[i]==p_list[i]]
    incorrect = [(X_list[i], y_list[i], p_list[i]) for i in range(len(y_list)) if y_list[i]!=p_list[i]]

    print("\n✅ CORRECT PREDICTIONS:")
    for txt, true, pred in correct[:3]:
        print(f"\nInput:  {txt[:200]}...")
        print(f"True:      {label_map[true]}")
        print(f"Predicted: {label_map[pred]} ✓")

    print("\n❌ INCORRECT PREDICTIONS (misclassified):")
    for txt, true, pred in incorrect[:2]:
        print(f"\nInput:  {txt[:200]}...")
        print(f"True:      {label_map[true]}")
        print(f"Predicted: {label_map[pred]} ✗")

# CELL 14 — GPT-3.5 Zero-Shot Prompting
from openai import OpenAI
import time

client = OpenAI(api_key="GPT3.5 API KEY")

PROMPT = """You are an expert at detecting AI-generated text.

Read the following text and classify it as either HUMAN or AI.

- HUMAN: written by a real person
- AI: generated by an AI like ChatGPT

Text:
\"\"\"
{text}
\"\"\"

Respond with exactly one word: HUMAN or AI"""

def classify_gpt(text, max_chars=500):
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role":"user","content":PROMPT.format(text=text[:max_chars])}],
            max_tokens=5,
            temperature=0,
        )
        answer = response.choices[0].message.content.strip().upper()
        if "HUMAN" in answer: return 0
        elif "AI" in answer:   return 1
        else:                  return -1
    except Exception as e:
        print(f"Error: {e}")
        return -1

def eval_gpt(X_test, y_test, name, n=200):
    print(f"\n{'='*50}")
    print(f"GPT-3.5 ZERO-SHOT — {name} (n={n})")
    print(f"{'='*50}")
    X_s = list(X_test)[:n]
    y_s = list(y_test)[:n]
    preds = []
    for i, text in enumerate(X_s):
        preds.append(classify_gpt(text))
        if (i+1) % 50 == 0:
            print(f"  {i+1}/{n} done...")
        time.sleep(0.5)
    valid = [(p,t) for p,t in zip(preds,y_s) if p!=-1]
    p_clean = [v[0] for v in valid]
    t_clean = [v[1] for v in valid]
    acc = accuracy_score(t_clean, p_clean)
    print(f"\nAccuracy: {acc:.4f}")
    print(classification_report(t_clean, p_clean, target_names=["Human","AI"]))
    return acc

gpt_hc3  = eval_gpt(X_te_hc3,  y_te_hc3,  "HC3")
gpt_nyt  = eval_gpt(X_te_nyt,  y_te_nyt,  "NYT")
gpt_raid = eval_gpt(X_te_raid, y_te_raid, "RAID")

print(f"\n✅ GPT done!")
print(f"HC3:  {gpt_hc3:.4f}")
print(f"NYT:  {gpt_nyt:.4f}")
print(f"RAID: {gpt_raid:.4f}")

# CELL 15 — Final Results Summary
print("="*65)
print(f"{'Model':<25} {'HC3':>10} {'NYT':>10} {'RAID':>10}")
print("="*65)
print(f"{'Naive Bayes':<25} {results_hc3['Naive Bayes']*100:>9.1f}% {results_nyt['Naive Bayes']*100:>9.1f}% {results_raid['Naive Bayes']*100:>9.1f}%")
print(f"{'Logistic Regression':<25} {results_hc3['Logistic Regression']*100:>9.1f}% {results_nyt['Logistic Regression']*100:>9.1f}% {results_raid['Logistic Regression']*100:>9.1f}%")
print(f"{'Linear SVM':<25} {results_hc3['Linear SVM']*100:>9.1f}% {results_nyt['Linear SVM']*100:>9.1f}% {results_raid['Linear SVM']*100:>9.1f}%")
print(f"{'DistilBERT':<25} {bert_hc3*100:>9.1f}% {bert_nyt*100:>9.1f}% {bert_raid*100:>9.1f}%")
print(f"{'GPT-3.5 Zero-Shot':<25} {gpt_hc3*100:>9.1f}% {gpt_nyt*100:>9.1f}% {gpt_raid*100:>9.1f}%")
print("="*65)

# CELL 16 — Download everything
from google.colab import files
files.download("accuracy_comparison.png")
files.download("confusion_matrices.png")
files.download("dataset_difficulty.png")

# CELL 16 — Regenerate all plots with GPT-3.5 included
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

datasets = ["HC3\n(Medical/Legal)", "NYT\n(News)", "RAID\n(Multi-domain)"]
models   = ["Naive Bayes", "Logistic Reg.", "Linear SVM", "DistilBERT", "GPT-3.5 0-shot"]
colors   = ["#1A3A6B", "#2A5A9B", "#0D9488", "#14B8A6", "#7C3AED"]

scores = {
    "Naive Bayes":     [84.1, 96.5, 68.5],
    "Logistic Reg.":   [90.0, 98.7, 75.6],
    "Linear SVM":      [90.0, 99.2, 74.8],
    "DistilBERT":      [98.2, 99.7, 83.0],
    "GPT-3.5 0-shot":  [33.5, 45.5, 50.3],
}

# PLOT 1 — Grouped bar chart all models
fig, ax = plt.subplots(figsize=(14, 6))
x = np.arange(len(datasets))
w = 0.15
for idx, (model, vals) in enumerate(scores.items()):
    bars = ax.bar(x + idx*w, vals, w, label=model, color=colors[idx])
    for bar in bars:
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,
                f"{bar.get_height():.1f}", ha="center", fontsize=7.5, fontweight="bold")
ax.set_xticks(x + w*2)
ax.set_xticklabels(datasets, fontsize=12)
ax.set_ylim(25, 108)
ax.set_ylabel("Accuracy (%)", fontsize=13)
ax.set_title("Model Accuracy Across All Datasets", fontsize=15, fontweight="bold")
ax.legend(fontsize=10)
ax.spines[["top","right"]].set_visible(False)
ax.axhline(y=50, color="red", linestyle="--", linewidth=1, alpha=0.5, label="Random baseline")
plt.tight_layout()
plt.savefig("accuracy_all_models.png", dpi=150)
plt.show()
print("✅ Plot 1 saved")

# PLOT 2 — Confusion matrices SVM
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for ax, (X_tr, X_te, y_tr, y_te, name) in zip(axes, [
    (X_tr_hc3,  X_te_hc3,  y_tr_hc3,  y_te_hc3,  "HC3"),
    (X_tr_nyt,  X_te_nyt,  y_tr_nyt,  y_te_nyt,  "NYT"),
    (X_tr_raid, X_te_raid, y_tr_raid, y_te_raid, "RAID"),
]):
    tfidf = TfidfVectorizer(stop_words="english", max_features=5000)
    svm   = LinearSVC(max_iter=2000)
    svm.fit(tfidf.fit_transform(X_tr), y_tr)
    preds = svm.predict(tfidf.transform(X_te))
    cm    = confusion_matrix(y_te, preds)
    disp  = ConfusionMatrixDisplay(cm, display_labels=["Human","AI"])
    disp.plot(ax=ax, colorbar=False, cmap="Blues")
    ax.set_title(f"SVM — {name}", fontsize=12, fontweight="bold")
plt.suptitle("Confusion Matrices (Linear SVM)", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("confusion_matrices.png", dpi=150)
plt.show()
print("✅ Plot 2 saved")

# PLOT 3 — BERT vs GPT comparison
fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(datasets))
w = 0.3
b1 = ax.bar(x - w/2, [98.2, 99.7, 83.0], w, label="DistilBERT (fine-tuned)", color="#14B8A6")
b2 = ax.bar(x + w/2, [33.5, 45.5, 50.3], w, label="GPT-3.5 (zero-shot)",     color="#7C3AED")
for bar in list(b1)+list(b2):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,
            f"{bar.get_height():.1f}%", ha="center", fontsize=11, fontweight="bold")
ax.set_xticks(x)
ax.set_xticklabels(datasets, fontsize=12)
ax.set_ylim(25, 108)
ax.set_ylabel("Accuracy (%)", fontsize=13)
ax.set_title("Fine-tuned BERT vs LLM Zero-Shot Prompting", fontsize=14, fontweight="bold")
ax.axhline(y=50, color="red", linestyle="--", linewidth=1, alpha=0.5)
ax.text(2.55, 51.5, "Random baseline", fontsize=9, color="red")
ax.legend(fontsize=11)
ax.spines[["top","right"]].set_visible(False)
plt.tight_layout()
plt.savefig("bert_vs_gpt.png", dpi=150)
plt.show()
print("✅ Plot 3 saved")

# PLOT 4 — Dataset difficulty
fig, ax = plt.subplots(figsize=(9, 5))
x = np.arange(len(datasets))
w = 0.2
for idx, (model, vals, color) in enumerate([
    ("Naive Bayes",    [84.1, 96.5, 68.5], "#1A3A6B"),
    ("Linear SVM",     [90.0, 99.2, 74.8], "#0D9488"),
    ("DistilBERT",     [98.2, 99.7, 83.0], "#14B8A6"),
    ("GPT-3.5 0-shot", [33.5, 45.5, 50.3], "#7C3AED"),
]):
    ax.plot(datasets, vals, "o-", label=model, color=color, linewidth=2, markersize=8)
ax.set_ylim(25, 105)
ax.set_ylabel("Accuracy (%)", fontsize=13)
ax.set_title("How Accuracy Changes Across Dataset Difficulty", fontsize=13, fontweight="bold")
ax.axhline(y=50, color="red", linestyle="--", linewidth=1, alpha=0.4)
ax.legend(fontsize=10)
ax.spines[["top","right"]].set_visible(False)
plt.tight_layout()
plt.savefig("dataset_difficulty.png", dpi=150)
plt.show()
print("✅ Plot 4 saved")

print("\n✅ All 4 plots done!")

# CELL 17 — Download all plots
from google.colab import files
files.download("accuracy_all_models.png")
files.download("confusion_matrices.png")
files.download("bert_vs_gpt.png")
files.download("dataset_difficulty.png")

# CELL 17 — Download all plots
from google.colab import files
files.download("accuracy_all_models.png")
files.download("confusion_matrices.png")
files.download("bert_vs_gpt.png")
files.download("dataset_difficulty.png")